#!/bin/bash
appname="cf"
region="us-west-2"
bucketname="vulndb7vjuthhndnvi5"

function test_stack {
    url=$(aws cloudformation describe-stacks --stack-name cf --region us-west-2 --query "Stacks[].Outputs" | grep https | sed 's/"OutputValue": "//g' | sed 's/"//g' | awk '{$1=$1};1')
    #cat sam-app/events/SCAN_event.json > utils/event.json
    ./utils/test_stack_deploy.sh "-X GET $url"
    echo ""
}

if [ "$1" == "create" ]
then
    # Create Bucket
    aws s3 mb s3://$bucketname --region $region
    sam init --runtime python3.7
    cd sam-app
    sam build
    sam package --output-template packaged.yaml --s3-bucket $bucketname
    sam deploy --template-file packaged.yaml --region $region \
      --capabilities CAPABILITY_IAM --stack-name $appname
    aws cloudformation describe-stacks --stack-name $appname --region us-west-2 --query "Stacks[].Outputs"
elif [ "$1" == "modify" ]
then
    cd sam-app
    sam build
    sam package --output-template packaged.yaml --s3-bucket $bucketname
    sam deploy --template-file packaged.yaml --region $region \
      --capabilities CAPABILITY_IAM --stack-name $appname
    aws cloudformation describe-stacks --stack-name $appname --region us-west-2 --query "Stacks[].Outputs"
    test_stack
elif [ "$1" == "delete" ]
then
    # Remove Bucket
    aws s3 rb s3://$bucketname --region $region --force

    # Remove Stack
    aws cloudformation delete-stack --stack-name $appname
    #rm -rf sam-app/
elif [ "$1" == "test" ]
then
  test_stack
else
    echo 'USAGE: ./stack < create | modify | delete | test >'
fi

