Resources:
  IAMP4G4TD:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - codestar_dev
        - lambda_dev
      LoginProfile:
        Password: "!QAZzaq1!QAZzaq1"
        PasswordResetRequired: False
      Path: "/"
      UserName: sysadmin_dev
