AWSTemplateFormatVersion: '2010-09-09'
Description: 'vulndb app

  Modify vulnerability status via API

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  VulnDBApi:
    Description: API Gateway endpoint URL for Prod stage for VulnDB function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/vulndb/
  VulnDBFunction:
    Description: VulnDB Lambda Function ARN
    Value:
      Fn::GetAtt:
      - VulnDBFunction
      - Arn
  VulnDBFunctionIamRole:
    Description: Implicit IAM Role created for VulnDB function
    Value:
      Fn::GetAtt:
      - VulnDBFunctionRole
      - Arn
Resources:
  VulnDBFunction:
    Properties:
      CodeUri: s3://vulndb7vjuthhndnvi5/99a10fb6eca4807104617c652a4d0298
      Events:
        VulnDB:
          Properties:
            Method: ANY
            Path: /vulndb
          Type: Api
      Handler: app.lambda_handler
      Policies:
      - DynamoDBCrudPolicy:
          AccountId: ${AWS::AccountId}
          Partition: AWS
          Region: ${AWS::Region}
          TableName: checklist_redhat
      - DynamoDBReadPolicy:
          AccountId: ${AWS::AccountId}
          Partition: AWS
          Region: ${AWS::Region}
          TableName: checklist_redhat
      Runtime: python3.7
    Type: AWS::Serverless::Function
  myDynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: stig_id
        AttributeType: S
      - AttributeName: stig_status
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: myGSI
        KeySchema:
        - AttributeName: stig_status
          KeyType: HASH
        Projection:
          NonKeyAttributes:
          - stig_id
          ProjectionType: INCLUDE
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
      KeySchema:
      - AttributeName: stig_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: checklist_redhat
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
