#!/bin/bash

aws cloudformation create-stack --stack-name groupsAWSDynamoDBVulnDB --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --template-body file://groups_AWSDynamoDBVulnDB.yaml
