AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'vulndb app

  Modify vulnerability status via API

  '
Globals:
  Function:
    Timeout: 3
Resources:
  VulnDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://vulndb7vjuthhndnvi5/29ef9d5b18d30f3f39b9423a61192f80
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        VulnDB:
          Type: Api
          Properties:
            Path: /vulndb
            Method: ANY
      Policies:
      - DynamoDBCrudPolicy:
          Partition: AWS
          Region: ${AWS::Region}
          AccountId: ${AWS::AccountId}
          TableName: checklist_redhat
      - DynamoDBReadPolicy:
          Partition: AWS
          Region: ${AWS::Region}
          AccountId: ${AWS::AccountId}
          TableName: checklist_redhat
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: checklist_redhat
      AttributeDefinitions:
      - AttributeName: stig_id
        AttributeType: S
      - AttributeName: stig_status
        AttributeType: S
      KeySchema:
      - AttributeName: stig_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      GlobalSecondaryIndexes:
      - IndexName: myGSI
        KeySchema:
        - AttributeName: stig_status
          KeyType: HASH
        Projection:
          NonKeyAttributes:
          - stig_id
          ProjectionType: INCLUDE
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
Outputs:
  VulnDBApi:
    Description: API Gateway endpoint URL for Prod stage for VulnDB function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/vulndb/
  VulnDBFunction:
    Description: VulnDB Lambda Function ARN
    Value:
      Fn::GetAtt:
      - VulnDBFunction
      - Arn
  VulnDBFunctionIamRole:
    Description: Implicit IAM Role created for VulnDB function
    Value:
      Fn::GetAtt:
      - VulnDBFunctionRole
      - Arn
