AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  genckl

  Sample SAM Template for genckl

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GenCklFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: genckl/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        GenCkl:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /genckl
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            Partition: AWS
            Region: ${AWS::Region}
            AccountId: ${AWS::AccountId}
            TableName: checklist_redhat
        - DynamoDBReadPolicy:
            Partition: AWS
            Region: ${AWS::Region}
            AccountId: ${AWS::AccountId}
            TableName: checklist_redhat




Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GenCklApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/genckl/"
  GenCklFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GenCklFunction.Arn
  GenCklFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GenCklFunctionRole.Arn
