Resources:
  IAMP4G4TE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Description: String
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      MaxSessionDuration: 3600
      Path: /service-role/
      RoleName: AWSDynamoDBVulnDBRole
  IAMP4G4TF:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: "dynamodb:*"
            Resource: "arn:aws:dynamodb:us-west-2:096412041307:table/checklist_redhat"
      PolicyName: AWSDynamoDBVulnDBPolicy
      Roles:
        - AWSDynamoDBVulnDBRole
  IAMP4G4TG:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "dynamodb:DeleteItem"
              - "dynamodb:GetItem"
              - "dynamodb:PutItem"
              - "dynamodb:Scan"
              - "dynamodb:UpdateItem"
            Resource: "arn:aws:dynamodb:us-west-2:096412041307:table/*"
      PolicyName: AWSLambdaMicroserviceExecutionRole
      Roles:
        - AWSDynamoDBVulnDBRole

