#!/bin/bash

aws cloudformation create-stack --stack-name dbAWSDynamoDBVulnDB --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --template-body file://db_AWSDynamoDBVulnDB.yaml
