Resources:
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "checklist_redhat_dev"
      AttributeDefinitions:
        -
          AttributeName: "stig_id"
          AttributeType: "S"
        -
          AttributeName: "status"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "stig_id"
          KeyType: "HASH"
        -
          AttributeName: "status"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "myGSI"
          KeySchema:
            -
              AttributeName: "status"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "stig_id"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
