AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lockdown app

  Modify vulnerability status via API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LockDownFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lockdown/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        LockDown:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /lockdown
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            Partition: AWS
            Region: ${AWS::Region}
            AccountId: ${AWS::AccountId}
            TableName: checklist_redhat
        - DynamoDBReadPolicy:
            Partition: AWS
            Region: ${AWS::Region}
            AccountId: ${AWS::AccountId}
            TableName: checklist_redhat
  myDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "checklist_redhat"
      AttributeDefinitions:
        -
          AttributeName: "stig_id"
          AttributeType: "S"
        -
          AttributeName: "stig_status"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "stig_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "myGSI"
          KeySchema:
            -
              AttributeName: "stig_status"
              KeyType: "HASH"
          Projection:
            NonKeyAttributes:
              - "stig_id"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LockDownApi:
    Description: "API Gateway endpoint URL for Prod stage for LockDown function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lockdown/"
  LockDownFunction:
    Description: "LockDown Lambda Function ARN"
    Value: !GetAtt LockDownFunction.Arn
  LockDownFunctionIamRole:
    Description: "Implicit IAM Role created for LockDown function"
    Value: !GetAtt LockDownFunctionRole.Arn
