Resources:
  IAMP4G4TE:
    Type: AWS::IAM::Group
    Properties:
      GroupName: lambda_dev
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Path: "/"
  IAMP4G4TF:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
              Effect: "Allow"
              Action:
                - "apigateway:PATCH"
                - "apigateway:DELETE"
                - "apigateway:PUT"
                - "apigateway:POST"
                - "apigateway:GET"
                - "iam:AttachRolePolicy"
                - "iam:DetachRolePolicy"
                - "iam:CreateRole"
                - "iam:DeleteRole"
                - "organizations:DescribeAccount"
                - "organizations:DescribeOrganization"
                - "organizations:DescribeOrganizationalUnit"
                - "organizations:ListChildren"
                - "organizations:ListParents"
                - "organizations:ListPoliciesForTarget"
                - "organizations:ListRoots"
                - "organizations:ListPolicies"
                - "organizations:ListTargetsForPolicy"
              Resource: "*"
      PolicyName: APIGatewayIAMDev
      Groups:
        - lambda_dev
    DependsOn: IAMP4G4TE
