#!/bin/bash

aws cloudformation create-stack --stack-name userAWSDynamoDBVulnDB --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --template-body file://user_AWSDynamoDBVulnDB.yaml
