#!/bin/bash

aws cloudformation create-stack --stack-name roleAWSDynamoDBVulnDB --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --template-body file://role_AWSDynamoDBVulnDB.yaml
