#!/bin/bash
appname="genckl"
region="us-west-2"
bucketname="${appname}7vjuthhndnvi5"

function test_stack {
    #url="https://3cg0j7c560.execute-api.us-west-2.amazonaws.com/default/tester"
    #url="https://omdul8jp29.execute-api.us-west-2.amazonaws.com/default/vulndb"
    url=$(aws cloudformation describe-stacks --stack-name $appname --region us-west-2 --query "Stacks[].Outputs" | grep https | sed 's/"OutputValue": "//g' | sed 's/"//g' | awk '{$1=$1};1')
    echo "POST Test"
    curl -i -X POST -d @setup/sam-app_files/POST_event.json \
      -H "Accept: application/json" \
      -H "Content-Type: application/json" \
      $url
    echo ""
    echo ""
}

function deploy_stack {
    cd $appname
    sam build
    sam package --output-template packaged.yaml --s3-bucket $bucketname
    sam deploy --template-file packaged.yaml --region $region \
      --capabilities CAPABILITY_IAM --stack-name $appname
    aws cloudformation describe-stacks --stack-name $appname --region us-west-2 --query "Stacks[].Outputs"

}

if [ "$1" == "create" ]
then
    # Create Bucket
    aws s3 mb s3://$bucketname --region $region
    deploy_stack
elif [ "$1" == "modify" ]
then
    deploy_stack
    #test_stack
elif [ "$1" == "delete" ]
then
    # Remove Bucket
    aws s3 rb s3://$bucketname --region $region --force

    # Remove Stack
    aws cloudformation delete-stack --stack-name $appname
    #rm -rf sam-app/
elif [ "$1" == "test" ]
then
  test_stack
else
    echo 'USAGE: ./stack < create | modify | delete | test >'
fi

